### ISSUE TITLE
请问你那个大众点评黄焖鸡米饭的js爬虫中class属性包含shop-review-wrap，我在网页源码里并没有看到这样的class

### ISSUE THREAD

**Issue by quantmod** [ShenJianShou/crawler_samples#1]
请问shop-review-wrap这个css标签你是从哪儿找到的，反正翻遍网页源码我是没有搜到

**Comment by ShenJianShou** [comment]
你好，是在这个页面上：http://www.dianping.com/shop/19336654/editmember

**Comment by quantmod** [comment]
**_哦原来如此，问一下有微信账号爬虫的代码？_**

**Comment by fangcheng0724** [comment]
![image](https://cloud.githubusercontent.com/assets/17701167/17124504/28ddbb3a-531e-11e6-8f42-f1993ab6a19b.png)
